// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelConnectHost(arg1) {
  return window['go']['app']['App']['CancelConnectHost'](arg1);
}

export function CancelConnectHostTerminal(arg1) {
  return window['go']['app']['App']['CancelConnectHostTerminal'](arg1);
}

export function CancelConnectTerminal(arg1) {
  return window['go']['app']['App']['CancelConnectTerminal'](arg1);
}

export function CheckForUpdate() {
  return window['go']['app']['App']['CheckForUpdate']();
}

export function CloseKubernetesPodShell(arg1) {
  return window['go']['app']['App']['CloseKubernetesPodShell'](arg1);
}

export function CloseTerminalSession(arg1) {
  return window['go']['app']['App']['CloseTerminalSession'](arg1);
}

export function ConfirmUnknownHostKey(arg1, arg2) {
  return window['go']['app']['App']['ConfirmUnknownHostKey'](arg1, arg2);
}

export function ConnectHost(arg1) {
  return window['go']['app']['App']['ConnectHost'](arg1);
}

export function ConnectHostTerminal(arg1) {
  return window['go']['app']['App']['ConnectHostTerminal'](arg1);
}

export function ConnectKubernetesCluster(arg1) {
  return window['go']['app']['App']['ConnectKubernetesCluster'](arg1);
}

export function ConnectTerminal(arg1) {
  return window['go']['app']['App']['ConnectTerminal'](arg1);
}

export function CreateKubernetesResource(arg1) {
  return window['go']['app']['App']['CreateKubernetesResource'](arg1);
}

export function CreateSnippet(arg1) {
  return window['go']['app']['App']['CreateSnippet'](arg1);
}

export function DeleteAWSIntegration(arg1) {
  return window['go']['app']['App']['DeleteAWSIntegration'](arg1);
}

export function DeleteGCPIntegration(arg1) {
  return window['go']['app']['App']['DeleteGCPIntegration'](arg1);
}

export function DeleteHost(arg1) {
  return window['go']['app']['App']['DeleteHost'](arg1);
}

export function DeleteHostGroup(arg1) {
  return window['go']['app']['App']['DeleteHostGroup'](arg1);
}

export function DeleteKeychainKey(arg1) {
  return window['go']['app']['App']['DeleteKeychainKey'](arg1);
}

export function DeleteKubernetesCluster(arg1) {
  return window['go']['app']['App']['DeleteKubernetesCluster'](arg1);
}

export function DeleteKubernetesPod(arg1) {
  return window['go']['app']['App']['DeleteKubernetesPod'](arg1);
}

export function DeleteKubernetesResource(arg1) {
  return window['go']['app']['App']['DeleteKubernetesResource'](arg1);
}

export function DeleteSnippet(arg1) {
  return window['go']['app']['App']['DeleteSnippet'](arg1);
}

export function DisconnectKubernetesCluster() {
  return window['go']['app']['App']['DisconnectKubernetesCluster']();
}

export function DownloadUpdate() {
  return window['go']['app']['App']['DownloadUpdate']();
}

export function ExecuteLocalCommand(arg1, arg2) {
  return window['go']['app']['App']['ExecuteLocalCommand'](arg1, arg2);
}

export function ExecuteSessionCommand(arg1, arg2) {
  return window['go']['app']['App']['ExecuteSessionCommand'](arg1, arg2);
}

export function ExecuteSessionCommandIsolated(arg1, arg2) {
  return window['go']['app']['App']['ExecuteSessionCommandIsolated'](arg1, arg2);
}

export function ExecuteSnippetBatch(arg1) {
  return window['go']['app']['App']['ExecuteSnippetBatch'](arg1);
}

export function ExecuteTerminalCommand(arg1) {
  return window['go']['app']['App']['ExecuteTerminalCommand'](arg1);
}

export function ExportHostsBackup(arg1) {
  return window['go']['app']['App']['ExportHostsBackup'](arg1);
}

export function ExportKeychainKey(arg1) {
  return window['go']['app']['App']['ExportKeychainKey'](arg1);
}

export function GenerateKeychainKey(arg1) {
  return window['go']['app']['App']['GenerateKeychainKey'](arg1);
}

export function GetAWSIntegration(arg1) {
  return window['go']['app']['App']['GetAWSIntegration'](arg1);
}

export function GetActiveKubernetesSession() {
  return window['go']['app']['App']['GetActiveKubernetesSession']();
}

export function GetAppSettings() {
  return window['go']['app']['App']['GetAppSettings']();
}

export function GetAutocompleteSuggestions(arg1, arg2) {
  return window['go']['app']['App']['GetAutocompleteSuggestions'](arg1, arg2);
}

export function GetGCPIntegration(arg1) {
  return window['go']['app']['App']['GetGCPIntegration'](arg1);
}

export function GetHost(arg1) {
  return window['go']['app']['App']['GetHost'](arg1);
}

export function GetHostSecretStatus(arg1) {
  return window['go']['app']['App']['GetHostSecretStatus'](arg1);
}

export function GetHostSecretValue(arg1) {
  return window['go']['app']['App']['GetHostSecretValue'](arg1);
}

export function GetHostStartupSnippet(arg1) {
  return window['go']['app']['App']['GetHostStartupSnippet'](arg1);
}

export function GetKubernetesDashboard(arg1) {
  return window['go']['app']['App']['GetKubernetesDashboard'](arg1);
}

export function GetKubernetesNamespaces() {
  return window['go']['app']['App']['GetKubernetesNamespaces']();
}

export function GetKubernetesPodLogs(arg1) {
  return window['go']['app']['App']['GetKubernetesPodLogs'](arg1);
}

export function GetKubernetesResourceDetail(arg1) {
  return window['go']['app']['App']['GetKubernetesResourceDetail'](arg1);
}

export function GetKubernetesResourceEvents(arg1) {
  return window['go']['app']['App']['GetKubernetesResourceEvents'](arg1);
}

export function GetKubernetesSecretValue(arg1) {
  return window['go']['app']['App']['GetKubernetesSecretValue'](arg1);
}

export function ImportHostsBackup(arg1, arg2) {
  return window['go']['app']['App']['ImportHostsBackup'](arg1, arg2);
}

export function ImportKeychainKey(arg1) {
  return window['go']['app']['App']['ImportKeychainKey'](arg1);
}

export function ListAWSIntegrations() {
  return window['go']['app']['App']['ListAWSIntegrations']();
}

export function ListGCPIntegrations() {
  return window['go']['app']['App']['ListGCPIntegrations']();
}

export function ListHostGroups() {
  return window['go']['app']['App']['ListHostGroups']();
}

export function ListHostVault() {
  return window['go']['app']['App']['ListHostVault']();
}

export function ListHosts() {
  return window['go']['app']['App']['ListHosts']();
}

export function ListKeychainKeys() {
  return window['go']['app']['App']['ListKeychainKeys']();
}

export function ListKnownHosts() {
  return window['go']['app']['App']['ListKnownHosts']();
}

export function ListKubernetesClusters() {
  return window['go']['app']['App']['ListKubernetesClusters']();
}

export function ListKubernetesPodPortForwards(arg1) {
  return window['go']['app']['App']['ListKubernetesPodPortForwards'](arg1);
}

export function ListKubernetesServicePortForwards(arg1) {
  return window['go']['app']['App']['ListKubernetesServicePortForwards'](arg1);
}

export function ListSnippets() {
  return window['go']['app']['App']['ListSnippets']();
}

export function ReadBackupFile(arg1) {
  return window['go']['app']['App']['ReadBackupFile'](arg1);
}

export function ReadJSONFile(arg1) {
  return window['go']['app']['App']['ReadJSONFile'](arg1);
}

export function RemoveKnownHost(arg1, arg2) {
  return window['go']['app']['App']['RemoveKnownHost'](arg1, arg2);
}

export function ResizeKubernetesPodShell(arg1) {
  return window['go']['app']['App']['ResizeKubernetesPodShell'](arg1);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['app']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function SaveAWSIntegration(arg1, arg2, arg3) {
  return window['go']['app']['App']['SaveAWSIntegration'](arg1, arg2, arg3);
}

export function SaveAppSettings(arg1) {
  return window['go']['app']['App']['SaveAppSettings'](arg1);
}

export function SaveBackupFile(arg1, arg2, arg3) {
  return window['go']['app']['App']['SaveBackupFile'](arg1, arg2, arg3);
}

export function SaveGCPIntegration(arg1, arg2, arg3) {
  return window['go']['app']['App']['SaveGCPIntegration'](arg1, arg2, arg3);
}

export function SaveHost(arg1, arg2) {
  return window['go']['app']['App']['SaveHost'](arg1, arg2);
}

export function SaveHostGroup(arg1) {
  return window['go']['app']['App']['SaveHostGroup'](arg1);
}

export function SaveJSONFile(arg1, arg2) {
  return window['go']['app']['App']['SaveJSONFile'](arg1, arg2);
}

export function SaveKubernetesCluster(arg1) {
  return window['go']['app']['App']['SaveKubernetesCluster'](arg1);
}

export function SaveKubernetesPodLogs(arg1, arg2) {
  return window['go']['app']['App']['SaveKubernetesPodLogs'](arg1, arg2);
}

export function SaveKubernetesResourceYAML(arg1, arg2) {
  return window['go']['app']['App']['SaveKubernetesResourceYAML'](arg1, arg2);
}

export function ScaleKubernetesResource(arg1) {
  return window['go']['app']['App']['ScaleKubernetesResource'](arg1);
}

export function SelectFile(arg1) {
  return window['go']['app']['App']['SelectFile'](arg1);
}

export function SetHostStartupSnippet(arg1) {
  return window['go']['app']['App']['SetHostStartupSnippet'](arg1);
}

export function StartKubernetesPodPortForward(arg1) {
  return window['go']['app']['App']['StartKubernetesPodPortForward'](arg1);
}

export function StartKubernetesPodShell(arg1) {
  return window['go']['app']['App']['StartKubernetesPodShell'](arg1);
}

export function StartKubernetesServicePortForward(arg1) {
  return window['go']['app']['App']['StartKubernetesServicePortForward'](arg1);
}

export function StartLocalTerminal(arg1) {
  return window['go']['app']['App']['StartLocalTerminal'](arg1);
}

export function StopKubernetesPodPortForward(arg1) {
  return window['go']['app']['App']['StopKubernetesPodPortForward'](arg1);
}

export function SwitchKubernetesContext(arg1) {
  return window['go']['app']['App']['SwitchKubernetesContext'](arg1);
}

export function SyncAWS(arg1) {
  return window['go']['app']['App']['SyncAWS'](arg1);
}

export function SyncGCP(arg1) {
  return window['go']['app']['App']['SyncGCP'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['app']['App']['TestConnection'](arg1);
}

export function TestHostConnection(arg1) {
  return window['go']['app']['App']['TestHostConnection'](arg1);
}

export function UpdateKubernetesResource(arg1) {
  return window['go']['app']['App']['UpdateKubernetesResource'](arg1);
}

export function UpdateSnippet(arg1) {
  return window['go']['app']['App']['UpdateSnippet'](arg1);
}

export function WriteKubernetesPodShellInput(arg1) {
  return window['go']['app']['App']['WriteKubernetesPodShellInput'](arg1);
}

export function WriteTerminalInput(arg1, arg2) {
  return window['go']['app']['App']['WriteTerminalInput'](arg1, arg2);
}
