// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {app} from '../models';

export function CancelConnectHost(arg1:string):Promise<dto.OperationResult>;

export function CancelConnectHostTerminal(arg1:dto.HostConnectionRequest):Promise<dto.OperationResult>;

export function CancelConnectTerminal(arg1:dto.SSHConfig):Promise<void>;

export function CheckForUpdate():Promise<app.UpdateInfo>;

export function CloseKubernetesPodShell(arg1:string):Promise<void>;

export function CloseTerminalSession(arg1:string):Promise<void>;

export function ConfirmUnknownHostKey(arg1:string,arg2:number):Promise<dto.OperationResult>;

export function ConnectHost(arg1:string):Promise<dto.OperationResult>;

export function ConnectHostTerminal(arg1:dto.HostConnectionRequest):Promise<dto.OperationResult>;

export function ConnectKubernetesCluster(arg1:dto.KubernetesConnectRequest):Promise<dto.KubernetesSession>;

export function ConnectTerminal(arg1:dto.SSHConfig):Promise<dto.OperationResult>;

export function CreateKubernetesResource(arg1:dto.KubernetesResourceCreateRequest):Promise<dto.KubernetesResourceCreateResult>;

export function CreateSnippet(arg1:dto.SnippetUpsertRequest):Promise<dto.Snippet>;

export function DeleteAWSIntegration(arg1:string):Promise<dto.OperationResult>;

export function DeleteGCPIntegration(arg1:string):Promise<dto.OperationResult>;

export function DeleteHost(arg1:string):Promise<dto.OperationResult>;

export function DeleteHostGroup(arg1:string):Promise<dto.OperationResult>;

export function DeleteKeychainKey(arg1:string):Promise<dto.OperationResult>;

export function DeleteKubernetesCluster(arg1:string):Promise<void>;

export function DeleteKubernetesPod(arg1:dto.KubernetesPodDeleteRequest):Promise<void>;

export function DeleteKubernetesResource(arg1:dto.KubernetesResourceDeleteRequest):Promise<void>;

export function DeleteSnippet(arg1:string):Promise<void>;

export function DisconnectKubernetesCluster():Promise<void>;

export function DownloadUpdate():Promise<app.DownloadResult>;

export function ExecuteLocalCommand(arg1:string,arg2:Record<string, string>):Promise<dto.OperationResult>;

export function ExecuteSessionCommand(arg1:string,arg2:string):Promise<dto.OperationResult>;

export function ExecuteSessionCommandIsolated(arg1:string,arg2:string):Promise<dto.OperationResult>;

export function ExecuteSnippetBatch(arg1:dto.ExecuteSnippetBatchRequest):Promise<dto.SnippetBatchResult>;

export function ExecuteTerminalCommand(arg1:dto.TerminalCommandRequest):Promise<dto.OperationResult>;

export function ExportHostsBackup(arg1:dto.HostExportOptions):Promise<dto.OperationResult>;

export function ExportKeychainKey(arg1:dto.ExportKeychainKeyRequest):Promise<dto.OperationResult>;

export function GenerateKeychainKey(arg1:dto.GenerateKeychainKeyRequest):Promise<dto.OperationResult>;

export function GetAWSIntegration(arg1:string):Promise<dto.OperationResult>;

export function GetActiveKubernetesSession():Promise<dto.KubernetesSession>;

export function GetAppSettings():Promise<dto.OperationResult>;

export function GetAutocompleteSuggestions(arg1:string,arg2:string):Promise<dto.AutocompleteResult>;

export function GetGCPIntegration(arg1:string):Promise<dto.OperationResult>;

export function GetHost(arg1:string):Promise<dto.OperationResult>;

export function GetHostSecretStatus(arg1:string):Promise<dto.OperationResult>;

export function GetHostSecretValue(arg1:dto.HostSecretValueRequest):Promise<dto.OperationResult>;

export function GetHostStartupSnippet(arg1:dto.SSHConfig):Promise<dto.HostStartupSnippet>;

export function GetKubernetesDashboard(arg1:dto.KubernetesDashboardRequest):Promise<dto.KubernetesDashboardSnapshot>;

export function GetKubernetesNamespaces():Promise<Array<string>>;

export function GetKubernetesPodLogs(arg1:dto.KubernetesPodLogsRequest):Promise<dto.KubernetesPodLogs>;

export function GetKubernetesResourceDetail(arg1:dto.KubernetesResourceDetailRequest):Promise<dto.KubernetesResourceDetail>;

export function GetKubernetesResourceEvents(arg1:dto.KubernetesResourceEventsRequest):Promise<dto.KubernetesResourceEvents>;

export function GetKubernetesSecretValue(arg1:dto.KubernetesSecretValueRequest):Promise<dto.KubernetesSecretValue>;

export function ImportHostsBackup(arg1:string,arg2:dto.HostImportOptions):Promise<dto.OperationResult>;

export function ImportKeychainKey(arg1:dto.ImportKeychainKeyRequest):Promise<dto.OperationResult>;

export function ListAWSIntegrations():Promise<dto.OperationResult>;

export function ListGCPIntegrations():Promise<dto.OperationResult>;

export function ListHostGroups():Promise<dto.OperationResult>;

export function ListHostVault():Promise<dto.OperationResult>;

export function ListHosts():Promise<dto.OperationResult>;

export function ListKeychainKeys():Promise<dto.OperationResult>;

export function ListKnownHosts():Promise<dto.OperationResult>;

export function ListKubernetesClusters():Promise<Array<dto.KubernetesClusterProfile>>;

export function ListKubernetesPodPortForwards(arg1:dto.KubernetesPodPortForwardListRequest):Promise<Array<dto.KubernetesPodPortForward>>;

export function ListKubernetesServicePortForwards(arg1:dto.KubernetesServicePortForwardListRequest):Promise<Array<dto.KubernetesPodPortForward>>;

export function ListSnippets():Promise<Array<dto.Snippet>>;

export function ReadBackupFile(arg1:string):Promise<dto.OperationResult>;

export function ReadJSONFile(arg1:string):Promise<dto.OperationResult>;

export function RemoveKnownHost(arg1:string,arg2:number):Promise<dto.OperationResult>;

export function ResizeKubernetesPodShell(arg1:dto.KubernetesPodShellSessionRequest):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<dto.OperationResult>;

export function SaveAWSIntegration(arg1:dto.AWSIntegration,arg2:dto.AWSIntegrationSecretsInput,arg3:string):Promise<dto.OperationResult>;

export function SaveAppSettings(arg1:dto.AppSettings):Promise<dto.OperationResult>;

export function SaveBackupFile(arg1:string,arg2:string,arg3:string):Promise<dto.OperationResult>;

export function SaveGCPIntegration(arg1:dto.GCPIntegration,arg2:dto.GCPIntegrationSecretsInput,arg3:string):Promise<dto.OperationResult>;

export function SaveHost(arg1:dto.HostProfile,arg2:dto.HostSecretsInput):Promise<dto.OperationResult>;

export function SaveHostGroup(arg1:dto.HostGroup):Promise<dto.OperationResult>;

export function SaveJSONFile(arg1:string,arg2:string):Promise<dto.OperationResult>;

export function SaveKubernetesCluster(arg1:dto.KubernetesClusterProfile):Promise<dto.KubernetesClusterProfile>;

export function SaveKubernetesPodLogs(arg1:string,arg2:string):Promise<string>;

export function SaveKubernetesResourceYAML(arg1:string,arg2:string):Promise<string>;

export function ScaleKubernetesResource(arg1:dto.KubernetesResourceScaleRequest):Promise<void>;

export function SelectFile(arg1:string):Promise<string>;

export function SetHostStartupSnippet(arg1:dto.HostStartupSnippetRequest):Promise<dto.HostStartupSnippet>;

export function StartKubernetesPodPortForward(arg1:dto.KubernetesPodPortForwardRequest):Promise<dto.KubernetesPodPortForward>;

export function StartKubernetesPodShell(arg1:dto.KubernetesPodShellStartRequest):Promise<dto.KubernetesPodShellSession>;

export function StartKubernetesServicePortForward(arg1:dto.KubernetesServicePortForwardRequest):Promise<dto.KubernetesPodPortForward>;

export function StartLocalTerminal(arg1:string):Promise<dto.OperationResult>;

export function StopKubernetesPodPortForward(arg1:dto.KubernetesPodPortForwardStopRequest):Promise<void>;

export function SwitchKubernetesContext(arg1:dto.KubernetesContextSwitchRequest):Promise<void>;

export function SyncAWS(arg1:string):Promise<dto.OperationResult>;

export function SyncGCP(arg1:string):Promise<dto.OperationResult>;

export function TestConnection(arg1:dto.SSHConfig):Promise<dto.OperationResult>;

export function TestHostConnection(arg1:string):Promise<dto.OperationResult>;

export function UpdateKubernetesResource(arg1:dto.KubernetesResourceUpdateRequest):Promise<dto.KubernetesResourceCreateResult>;

export function UpdateSnippet(arg1:dto.SnippetUpsertRequest):Promise<dto.Snippet>;

export function WriteKubernetesPodShellInput(arg1:dto.KubernetesPodShellSessionRequest):Promise<void>;

export function WriteTerminalInput(arg1:string,arg2:string):Promise<void>;
